name: mobile_tumbuh_sehat_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  camera: ^0.11.2
  connectivity_plus: ^6.1.5
  csv: ^6.0.0
  dartz: ^0.10.1
  midtrans_sdk: ^1.2.0
  dio: ^5.9.0
  equatable: ^2.0.7
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.0
  flutter_typeahead: ^5.2.0
  get_it: ^8.2.0
  image_picker: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  mesh_gradient: ^1.3.8
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0
  syncfusion_flutter_gauges: ^31.1.19
  midtrans_snap: ^1.0.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0
  json_serializable: ^6.11.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/db/
    - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800